# Generated by Django 6.0.6 on 2026-06-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Hi, I'm a Full Stack Developer", max_length=255)),
                ('hero_subtitle', models.TextField(default='Building robust systems and beautiful user experiences.')),
                ('currently_learning', models.CharField(default='Django, Python, Advanced DevOps', max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('profile_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('email', models.EmailField(default='hello@developer.com', max_length=254)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('about_text', models.TextField(default="I'm a dedicated Full Stack Developer with a strong focus on building scalable web applications and delivering seamless user experiences. I bridge the gap between complex backend logic and intuitive frontend designs.")),
                ('experience_years', models.CharField(default='2.5', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
