# Generated by Django 6.0.6 on 2026-06-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteprofile_blog_image_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Where contact form messages should be sent.', max_length=254, null=True),
        ),
    ]
