# Generated by Django 6.0.2 on 2026-08-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='about_heading',
            field=models.CharField(default='Crafting thoughtful digital experiences with code and creativity', max_length=255),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='about_subheading',
            field=models.TextField(default='From intuitive interfaces to robust backend systems, I focus on creating experiences that are fast, modern, and impactful.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='footer_copyright',
            field=models.CharField(default='© 2026 Ahsan Manzoor. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='footer_description',
            field=models.TextField(default='Crafting elegant digital experiences with Python, Django, and AI-driven product thinking.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='footer_title',
            field=models.CharField(default='Ahsan Portfolio', max_length=100),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='hero_badge',
            field=models.CharField(default='AI-Driven Developer', max_length=80),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='hero_highlight',
            field=models.CharField(default='Python • Django • AI Products', max_length=120),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='site_title',
            field=models.CharField(default='Ahsan Portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='about_text',
            field=models.TextField(default='I blend product thinking, scalable architecture, and AI-driven automation to deliver polished web applications that feel effortless for users and reliable for businesses.'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='currently_learning',
            field=models.CharField(default='Django, Python, Advanced AI & Automation', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='hero_subtitle',
            field=models.TextField(default='I build polished products with Python, Django, modern frontend stacks, and AI-driven experiences.'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='hero_title',
            field=models.CharField(default='Hi, I’m Ahsan — Full Stack Developer & AI Builder', max_length=255),
        ),
    ]
