# Generated by Django 6.0.2 on 2026-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_journeyitem_repository_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Tools', 'Tools'), ('Database', 'Database')], max_length=20),
        ),
    ]
