# Generated by Django 6.0.2 on 2026-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='footer_about_text',
            field=models.TextField(default="I'm Ahsan Manzoor, a MERN Stack & AI Developer passionate about building scalable web applications and agentic AI systems that solve real-world problems.", help_text='Short bio shown in the About column of the footer.'),
        ),
    ]
