# Generated by Django 6.0.2 on 2026-08-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteprofile_footer_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Agents', 'Agents'), ('AI Assistant', 'AI Assistant')], default='Full Stack', max_length=20),
        ),
    ]
